{{- if .Values.database.createSecret }}
{{- if not .Values.database.existingSecret }}
{{- if .Values.database.connectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pylight.secretName" . }}
  labels:
    {{- include "pylight.labels" . | nindent 4 }}
type: Opaque
data:
  connection-string: {{ .Values.database.connectionString | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}

