apiVersion: v2
name: pylight
description: Helm chart for deploying Pylight CRUD APIs to Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - api
  - rest
  - crud
  - python
  - pylight
home: https://github.com/iklobato/pylight
sources:
  - https://github.com/iklobato/pylight
maintainers:
  - name: Pylight Team
annotations:
  artifacthub.io/changes: |
    - Initial release of Helm chart for Pylight
